### ISSUE TITLE
Biometrics Support

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziAccessGuard#6]
### Problem

The current access guard module does not support guarding a view using biometrics such as TouchID or FaceID.

### Solution

The `AccessGuarded` view should default to a biometrics-based solution if configured by the developer. A skeleton of these configuration options are currently already in the repository and are hidden behind a private access modifier.

### Additional context

You can learn more about the API surface here: https://developer.apple.com/documentation/localauthentication/logging_a_user_into_your_app_with_face_id_or_touch_id/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Addressed by #18.
